import type { Level3Case } from './level3.types'

export const LEVEL3_DURATION_SECONDS = 180
export const LEVEL3_INITIAL_GUIDE_MESSAGE = '左右滑动并点编号，\n找出5起可疑行为'

export const level3Cases: readonly Level3Case[] = [
  {
    id: 'personal-duty-free-pickup',
    number: 1,
    zone: 'duty-free',
    category: '离岛免税',
    title: '离岛免税提货现场',
    scene: '旅客持本人有效证件和船票，在提货点领取自己购买的免税商品，准备带离海南自用。',
    dialogue: [
      { speaker: '工作人员', text: '请出示您本人的身份证件、离岛票和购物凭证。' },
      { speaker: '旅客', text: '都在这里，这些是我自己购买、准备自用的商品。' },
    ],
    clues: ['购买、支付和提货信息均为本人', '商品自用并妥善保留购物凭证'],
    judgment: 'normal',
    observationHint: '留意证件、离岛票和购物凭证是否为本人，商品是否用于个人自用。',
    educationPoint: '本人按规定购买和提取自用免税商品属于正常行为，不能因购买免税品就误报。',
    signalPosition: { x: 10.5, y: 39 },
  },
  {
    id: 'organized-duty-free-collection',
    number: 2,
    zone: 'duty-free',
    category: '离岛免税',
    title: '免税商品集中交接',
    scene: '多名旅客将免税购物袋集中交给一名收货人，购物数量明显超出个人自用范围。',
    dialogue: [
      { speaker: '收货人', text: '大家把购物袋都放到车上，我核对完就结算“辛苦费”。' },
      { speaker: '旅客', text: '这些都是按你发的清单买的，我没有打开过。' },
    ],
    clues: ['多人商品被同一人集中回收', '按他人清单购买并收取报酬'],
    judgment: 'report',
    observationHint: '留意人员关系、购买数量和商品交接方式。',
    educationPoint: '组织多人利用离岛免税资格集中购货、回收转卖牟利，是“套代购”风险线索。',
    signalPosition: { x: 20, y: 18 },
  },
  {
    id: 'luxury-electronics-mismatch',
    number: 3,
    zone: 'priority-goods',
    category: '高档消费品·电子产品',
    title: '商品申报查验',
    scene: '货物清单标注为普通服装，开箱后却发现成批手机、相机、腕表和高档箱包。',
    dialogue: [
      { speaker: '理货员', text: '清单上写的是普通服装，怎么里面全是手机、腕表和箱包？' },
      { speaker: '搬运工', text: '别管这么多，赶快按普通货物运出去。' },
    ],
    clues: ['实际货物与申报品名不一致', '高档商品和电子产品成批藏在普通纸箱中'],
    judgment: 'report',
    observationHint: '对照申报清单与箱内实际货物，留意品名和数量是否一致。',
    educationPoint: '高档消费品、电子产品与申报明显不符并逃避监管时，应及时报告。',
    signalPosition: { x: 32, y: 37 },
  },
  {
    id: 'concealed-tobacco',
    number: 4,
    zone: 'priority-goods',
    category: '烟草',
    title: '货箱搬运现场',
    scene: '几个标注为日用品的纸箱内，实际夹藏着大量未申报的卷烟。',
    dialogue: [
      { speaker: '搬运工甲', text: '把这些烟压在日用品下面，外箱照旧封好。' },
      { speaker: '搬运工乙', text: '我们从旁边的通道运走，别经过正常查验口。' },
    ],
    clues: ['申报服装却夹藏大量卷烟', '车辆避开正常检查通道'],
    judgment: 'report',
    observationHint: '留意纸箱申报内容、实际货物，以及搬运路线是否经过正常查验。',
    educationPoint: '申报与实际货物不符并逃避检查，是重点商品走私的重要风险线索。',
    signalPosition: { x: 43, y: 48 },
  },
  {
    id: 'compliant-frozen-seafood-inspection',
    number: 5,
    zone: 'priority-goods',
    category: '冻海产品',
    title: '冻海产品检验交接',
    scene: '海关人员在冷链区核对冻海产品单证、温度记录并进行抽样检查。',
    dialogue: [
      { speaker: '海关人员', text: '货物品名和数量与单证一致，我们再核对冷链温度。' },
      { speaker: '冷链工作人员', text: '运输全程的温度记录和检验资料都在这里。' },
    ],
    clues: ['货物、数量与单证一致', '冷链温度和检验记录完整'],
    judgment: 'normal',
    observationHint: '核对单证、品名数量、冷链温度记录和查验流程是否完整。',
    educationPoint: '冻海产品经如实申报、冷链记录完整并正常接受查验，属于合规作业。',
    signalPosition: { x: 55, y: 18 },
  },
  {
    id: 'irregular-frozen-seafood-transfer',
    number: 6,
    zone: 'priority-goods',
    category: '冻海产品',
    title: '冻海产品岸边转运',
    scene: '工人在未设查验点的岸边，将无标识小船上的冻海产品直接搬到手推车。',
    dialogue: [
      { speaker: '船员', text: '这批冻鱼没有申报单，先从这个小码头卸下来。' },
      { speaker: '接货人', text: '装上手推车就走，不要进冷链查验区。' },
    ],
    clues: ['从无标识小船直接卸货', '无法提供申报和冷链检验资料'],
    judgment: 'report',
    observationHint: '留意卸货地点、船舶标识，以及是否具备申报和冷链检验资料。',
    educationPoint: '绕开正常码头和冷链查验，且无法提供单证的冻海产品转运，应立即报告。',
    signalPosition: { x: 66, y: 37 },
  },
  {
    id: 'compliant-fuel-loading',
    number: 7,
    zone: 'priority-goods',
    category: '成品油',
    title: '成品油装卸作业',
    scene: '工作人员在指定泊位使用正规流量设备装卸成品油，现场设有围挡和溢漏防护。',
    dialogue: [
      { speaker: '作业人员', text: '许可单证和今日作业台账已经核对，数量一致。' },
      { speaker: '安全员', text: '防溢漏围挡已展开，请按指定流程开始装卸。' },
    ],
    clues: ['许可、台账和作业数量一致', '在指定泊位并配备防溢漏设施'],
    judgment: 'normal',
    observationHint: '核对作业泊位、许可台账、装卸数量与防溢漏措施。',
    educationPoint: '手续齐全、台账相符并在指定泊位安全作业，属于正常的成品油运输。',
    signalPosition: { x: 79, y: 31 },
  },
  {
    id: 'offshore-fuel-transfer',
    number: 8,
    zone: 'priority-goods',
    category: '成品油',
    title: '成品油水上转运',
    scene: '两艘小船在非指定作业水域靠拢，使用临时软管在油桶之间转运油品。',
    dialogue: [
      { speaker: '小船甲', text: '把软管接过来，这里没有查验点，转完就走。' },
      { speaker: '小船乙', text: '这批油没有运输凭证，油桶上也不要留标识。' },
    ],
    clues: ['非指定水域使用临时软管接驳', '无法提供合法运输和交易凭证'],
    judgment: 'report',
    observationHint: '留意作业水域、转运设备，以及油品运输凭证是否齐全。',
    educationPoint: '在非指定水域私接软管过驳、来源去向不明且无单证，是成品油走私风险线索。',
    signalPosition: { x: 91, y: 17 },
  },
] as const

export const LEVEL3_CASE_TOTAL = level3Cases.length
export const LEVEL3_REPORT_TOTAL = level3Cases.filter(
  (caseItem) => caseItem.judgment === 'report',
).length
